services:
  postgres:
    container_name: postgres-time-ms
    image: postgres:16.3
    environment:
      POSTGRES_USER: time-ms
      POSTGRES_PASSWORD: time-ms
    volumes:
      - postgres_volume_new:/var/lib/postgresql/data
    networks:
      - time-ms-network
    ports:
      - "5442:5432"
    restart: unless-stopped

networks:
  time-ms-network:
    driver: bridge

volumes:
  postgres_volume_new: