server:
  port: 8082

spring:
  application:
    name: time-ms
  datasource:
    driver-class-name: org.postgresql.Driver
    username: time-ms
    password: time-ms
    url: jdbc:postgresql://localhost:5442/time-ms
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false

multitenancy:
  main:
    liquibase:
      change-log: db/changelog/main/main-changelog.yaml
  tenant:
    default-tenant: public
    liquibase:
      change-log: db/changelog/tenant/tenant-changelog.yaml

app:
  config:
    google-client-id: 767173580299-fcnbh5h922avn99lktktjb9uq9f5itcc.apps.googleusercontent.com
  cors:
    allowed-origins:
      - http://localhost:*
      - http://127.0.0.1:*