server:
  port: 8082

spring:
  application:
    name: time-craft
  datasource:
    driver-class-name: org.postgresql.Driver
    username: time-craft
    password: time-craft
    url: jdbc:postgresql://localhost:5441/time-craft
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false

  liquibase:
    change-log: db/changelog/main-changelog.yaml

app:
  time-config:
    offset: 0
    startHourOfWorkingDay: 7
    endHourOfWorkingDay: 17
  cors:
    allowed-origins:
      - http://localhost:*
      - http://127.0.0.1:*
  jira:
    url: https://craftcodelab.atlassian.net
    email: andrii@craftcodelab.com
    token: ATATT3xFfGF0sMt4mhbcVyi_9h-YSNKI1R6VqCT43Ramds_f2o_huMXHWcBHxLe2JNmh1vhpbvi8GiSCypHVws1mZLEO7A72K4SDidQkOnDF7wSZlxKa3IVazt3u-ilB01bBdTrQzCd5X72pUp-vmnBbd07PHim2ywBLOz3WsnxuM6texmAdDiM=D4E04AFB

