server:
  port: 8082

spring:
  application:
    name: time-craft
  datasource:
    driver-class-name: org.postgresql.Driver
    username: time-craft
    password: time-craft
    url: jdbc:postgresql://localhost:5441/time-craft
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false

  liquibase:
    change-log: db/changelog/main-changelog.yaml

app:
  config:
    is-jira-syncing-enabled: true
    upwork-time-cf: 2
    offset: 3
    start-hour-of-working-day: 7
    end-hour-of-working-day: 17
    working-day-duration-in-hours: 8
  cors:
    allowed-origins:
      - http://localhost:*
      - http://127.0.0.1:*
  jira:
    url: https://craftcodelab.atlassian.net
    email: <EMAIL>
    token: <JIRA_TOKEN>