databaseChangeLog:
  - changeSet:
      id: task/TMC-57-user-config-2
      author: Andrii Snovyda
      changes:
        - modifyDataType:
            tableName: config
            columnName: external_service_time_cf
            newDataType: double